### ISSUE TITLE
SA probabilistic

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#105]
Set reasonable rounding in table output. Now the values shown are too precise and do not look nice.

**Comment by mwasiluk** [comment]
2 decimal places or more?

**Comment by bkamins** [comment]
can you use information from global settings (where user sets number of decimal places)?

**Comment by mwasiluk** [comment]
I can use same payoff number format as in the diagram

**Comment by bkamins** [comment]
OK
