### ISSUE TITLE
SA - probabilistic

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#107]
`Totals` column is not needed. Do you see any value from this column?

**Comment by mwasiluk** [comment]
It's the only clickable column for policy preview.

**Comment by bkamins** [comment]
Can you then change this value to some text like "policy preview"?

Additional requirements:
* variables should be selected from a list of variables defined in global scope
* add `info outline` material design icon after formula with the following text `example formula random() samples a random value from interval from 0 to 1`; this text will be changed when #98 is implemented; also then we might add a selector of distributions from a list
* number of runs must be a strict integer (now floats are allowed an rounded)
* #110 should be also handled in the case of calculated values (mean, median, ...) properly
* when wrong expression is passed as value of variable (i.e. for which parsing fails) some sensible alert should be shown (now it shows red bar in computation view, but it is not clear what went wrong)

**Comment by bkamins** [comment]
OK. Except that similar to #109 when the variable is used twice I would highlight the second usage in red.

**Comment by bkamins** [comment]
OK
