### ISSUE TITLE
SA: large results

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#112]
There are two issues in large SA.

* SA is very large (N-way or Probabilistic)
@mwasiluk please check a reasonable value (probably 100,000 is reasonably large)
In SA definition dialog box if user enters parameters that result in more scenarios than this value some warning should appear like:
> Number of defined scenarios larger than 100,000. Sensitivity analysis might fail to compute or be very slow.

* In N-way SA if there are many parameters over which we perform sweep.
In SA definition dialog box if user enters more than 2 parameters a warning should appear like:
> Number of parameters larger than 2. Sensitivity analysis display might fail or be very slow.

In display of SA we do not put in columns more than 2 parameters. If there are more than 2 parameters we put into columns first 2 parameters.
Additionally @mwasiluk will report an issue of FF to pivot table project.

Those two messages should combine if both conditions are met.

**Comment by bkamins** [comment]
1. Decrease 100,000 to 10,000 -> it is already very slow for 10,000
2. If an error was issued and data is corrected and `Run` is pressed actually warning is cleared only and run is not executed. You have to click `Run` for the second time. It is a minor issue, but could be corrected :)

**Comment by bkamins** [comment]
@mwasiluk I understand that you retain the warning about large number of parameters also in table view - it is OK.
Do you also retain warning about large number of computations (I have not checked as I did not have time to wait till 100,000 :))?

**Comment by mwasiluk** [comment]
yes, all warnings are retained until back is clicked/dialog is closed

**Comment by mwasiluk** [comment]
@bkamins Maybe we should check variable length before setting it as column in pivot table? E.g. if user defines one variable with length > 100 000 browser tab may crash on pivottable rendering, but if we filter this variable from the table columns user should be able to at least download a csv file with the result.

**Comment by bkamins** [comment]
1. Decrease limit to 10,000 as I have written earlier
2. Add rule to add variables to columns as long as less than 1000 columns would be generated (as 1000 should work smoothly - it works OK on Chrome). What do you think?

**Comment by mwasiluk** [comment]
OK

**Comment by bkamins** [comment]
OK. Leaving open for docs
