### ISSUE TITLE
SA: handling errors in IE

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#113]
@mwasiluk Under IE some cleanup of error handling of SA parameterization is required.
Example problem in N-way SA (in Rockefeller):
1. define variable pr
2. define variable pr second time
3. run (error shows - it is OK)
4. change second variable to sens
5. run - here we run into a bug; pr is still red and run is not performed (and should be)

**Comment by bkamins** [comment]
Under Edge validation also fails.

**Comment by mwasiluk** [comment]
It works for me under Edge.

**Comment by bkamins** [comment]
For me it does not work neither under IE nor Edge. I have pressed Ctrl-F5 :).
@pszufe please test error handling on your PC

**Comment by mwasiluk** [comment]
should be fixed with 066175f

**Comment by bkamins** [comment]
OK
