### ISSUE TITLE
Add SA translation files

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#114]
I will add translations and correct description if tooltip in Probabilistic SA.

@mwasiluk just one question - please let me know if all new strings are in single internatiozalization file or there are several places where you have put them

**Comment by mwasiluk** [comment]
Pivot table has own i18n mechanism. I've created pull request for missing polish locale 2 weeks ago:
https://github.com/nicolaskruchten/pivottable/pull/681

**Comment by bkamins** [comment]
Apart from this are the only changes in `src/i18n`?

**Comment by mwasiluk** [comment]
yes
