### ISSUE TITLE
MCDM: vusial highlight of max-min and min-max

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#118]
We discussed that in drop down menu with rules min-max and max-min could be highlighted somehow (e.g. different color). Is this possible?

**Comment by bkamins** [comment]
Following the discussion we will use the following design:

 1. Add `View` list on the left of `Rule` list. Currently `View` list should contain three values (in the future we might add other views):
    * `Criterion 1`
    * `Criterion 2`
    * `Two criteria`
2. By default value in `Value` field should be `Criterion 1`;
3. Choice of value in `Value` field should influence list of possible values in `Rule` in a natural way (i.e. `Criterion 1/2` is only old list of rules, `Two criteria` gives two new rules `max-min` and `min-max`)
4. `Criterion 1` should show view of the tree with only data from first element of payoff (this is more or less what we have now on production)
5. `Criterion 2` should show view of the tree with only data from second element of payoff (so exactly the same as above but for the second element of payoff with proper formatting of payoff following #120 )
6. `Two criteria` should show what we now have on dev (but corrected following #120)

Transition rules:
1. `Criterion 1` is `max` by default
2. `Criterion 2` is `min` by default
4. When switching form `Two-criteria` to `Criterion 1` appropriately first part of optimization rule is used (for `max-min` it is `max`, for `min-max` it is `min`); the same rule applies fro `Criterion 2` buy only second part of criterion is used;
5. When switching form `Criterion 1` to `Two-criteria` appropriately first part of optimization rule is derived from direction of `Criterion 1` (for 'max it is `max-min` , for `min` it is `min-max`; the same for all other types of rules); the same rule applies fro `Criterion 2` buy only second part of criterion is set;
6. `Two-criteria` criteria names are `Cost` and `Effect` by default (we leave it as this and do not try to guess names for the criteria even if it would imply that cost is maximized or effect is minimized; let user update it);

In this way (except for the transition of `Rules`) changing value of `Value` field does not change anything except for what is displayed (the underlying data is identical).

@mwasiluk If this is problematic (because default display always takes value from criterion 1 and it would be cumbersome to rewrite it to show criterion 2 as described above) we can live with only two values in `View` list `Criterion 1` and `Two criteria` (then probably we will rename `Criterion 1` to `One criterion`). Please let us know how you see it

**Comment by bkamins** [comment]
@mwasiluk The only additional feature is "binding" of objectives in Criterion 1 and Criterion 2. What I mean is that if the first is maximized then the second must be minimized (and if the first is minimized the second must be maximized). The problem is that now when you change from Criterion 1 to Criterion 2 the objective remains unchanged and then when you go back to Two-criteria the criterion order is reversed.
And switching the Criterion 1 should switch Criterion 2.

The binding pairs should be:
min <> max <> min-max
max <> min <> max-min
maxi-min <> mini-max <> max-min
maxi-max <> mini-min <> max-min
mini-min <> maxi-max <> min-max
mini-max <> maxi-min <> min-max

Changing the objective order in two-criteria should change Criterion 1 (and Criterion 2 respectively) in the following way:
max -> min
min -> max
maxi-min -> mini-max
maxi-max -> mini-min
mini-min -> maxi-max
mini-max -> maxi-min

@michaljakubczyk please confirm the bindings.

**Comment by bkamins** [comment]
# Major change of requirements
We shall add max-max and min-min objectives in two-criteria view.

Consequences:
1. On plot criterion 1 is on x-axis and criterion 2 on y-axis; in league table criterion 1 is always in column 3 and criterion 2 in column 4 (*this is a change as before maximized criterion was on x-axis and in column 3 always*)
2. Weight (currently called WTP) is always applied to criterion 1 (*this is a change as previously we have applied weight to maximized criterion*)
3. Criterion fliping should flip everything between criteria 1 and 2 and in particular `weight` should become `1/weight` in default value and lower and upper bound. Of course 0 should be mapped to Infinity and Infinity to 0. **we do not allow negative weights** 
5. For calculations of optimal decisions and league table sweeps over weights we actually define the following objective function `[criterion 1 coeff]*[criterion 1]*[weight]+[criterion 2 coeff]*[criterion 2]` that is maximized. `[criterion 1 coeff]` is `1` if criterion 1 is maximized and is `-1` if it is minimized. `[criterion 2 coeff]` is `1` if criterion 2 is maximized and is `-1` if it is minimized.
6. Moving between one- and two- criteria views is transparent (we do not have any restrictions now). two- criteria view simply reads data from criterion 1 and criterion 2. By default criterion 1 is max and criterion 2 is min. If in two-criteria view objective is changed the way single criteria objectives are changed is specified in the mapping in the post above this one.
7. labels in for WTP in Multiple Criteria section in left pane should be renamed (@bkamins will do it today)
8. Name `ICER` should be replaced by something else. @michaljakubczyk please propose what it should be in general (my feeling is that `incremental ratio`)

**Comment by bkamins** [comment]
@mwasiluk `incremental ratio` instead of `ICER` is confirmed.

One more comment for taking into account weight upper and lower bound in calculations:
1. always perform calculations on the whole range of weight from 0 to infinity
2. upper and lower bound are only used for display of potentially optimal values (if this is not clear call @michaljakubczyk and discuss with him).

Additionally `flip` operation should also flip lower and upper boud, i.e:

`lower` becomes `1/upper`
`upper` becomes `1/lower`

**Comment by mwasiluk** [comment]
How should  "binding" of objectives work with min-min and max-max?

**Comment by bkamins** [comment]
After the discussion we have the following rules.

Switch form 1 to 2 criteria: we simply read the direction of single criteria and map them to two-criteria case.

Switch form 2 to 1 criterion: we always map to `min` or `max` and we map two criteria (so the criterion that is not shown "remembers" what was selected in two-criteria case).

In particular when switching to two-cirteria we forget the "flavor" of single criterion (i.e. we do not handle `maxi-min`, `maxi-max` and `max` separately - everything is fused to `max`).

**Comment by bkamins** [comment]
Minor issue: when flipping `1/[interval border]` sometimes gets formatted as e.g. `0.(6)`. @michaljakubczyk do we leave it as-is or round it?

**Comment by bkamins** [comment]
We leave `0.(6)` as OK.
