### ISSUE TITLE
Scrolling in left menu does not work on safari

### ISSUE THREAD

**Issue by maciejkra** [SilverDecisions/SilverDecisions#119]
Left menu (Layout/details/Variables) in silver decision does not work on Safari browser.
It is particularly noticeable when user expands all of the menus and add a decision tree with many nodes.

**Comment by bkamins** [comment]
@michaljakubczyk can you please test it on http://bogumilkaminski.pl/sddev/? It should work OK.

**Comment by pszufe** [comment]
done
