### ISSUE TITLE
MCDM: display error on FireFox

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#121]
Dev of SD does not display properly on FireFox (reported by @pszufe and @michaljakubczyk).

**Comment by bkamins** [comment]
@mwasiluk under FF also changing Layout does not work properly (you press a button and nothing happens)

**Comment by mwasiluk** [comment]
Which version of firefox / os ?

**Comment by bkamins** [comment]
I have updated everything and it works on my PC now.
@pszufe & @michaljakubczyk please confirm that UI works for you and we can close this issue then.

This is the UI testing range (I am adding proposed testers):
* Windows: latest Chrome, latest FireFox, latest Edge, latest IE @pszufe @michaljakubczyk @bkamins
* Ubuntu: latest Chrome, latest FireFox @pszufe 
* OS X: latest Chrome, latest FireFox @michaljakubczyk 
* Android: latest Chrome on tablet and on smartphone @bkamins
