### ISSUE TITLE
Problem with paste (ctrl+v)

### ISSUE THREAD

**Issue by Ceiwark** [SilverDecisions/SilverDecisions#123]
w trakcie tworzenia drzewa kopiowanie i wklejenie gałęzi spowodowało wywołanie błędu w postaci wklejenia zmniejszonych węzłów
![bug_obiekty](https://cloud.githubusercontent.com/assets/28671611/26025220/d48bc2ac-37e2-11e7-8918-a542ba6691cd.JPG)
wprowadzenie opisu/etykiety  gałęzi przywróciło normalną wielkość węzła końcowego.

**Comment by pszufe** [comment]
Uprzejmie prosimy o informację o przeglądarce oraz o systetemie operacyjnym tak abyśmy mogli zreplikować ten błąd.

**Comment by Ceiwark** [comment]
Firefox 53.0.2.Windows 10.


      Od: pszufe <notifications@github.com>
 Do: SilverDecisions/SilverDecisions <SilverDecisions@noreply.github.com> 
DW: Ceiwark <ceiwark@yahoo.pl>; Author <author@noreply.github.com>
 Wysłane: 13:57 sobota, 2017-5-13
 Temat: Re: [SilverDecisions/SilverDecisions] Problem with paste (ctrl+v) (#123)
   
Uprzejmie prosimy o informację o przeglądarce oraz o systetemie operacyjnym tak abyśmy mogli zreplikować ten błąd.—

**Comment by bkamins** [comment]
@Ceiwark Czy po naciśnięciu Ctrl-F5 (to powinno wyczyścić cache przeglądarki) błąd ciągle występuje.

Przetestowałem `Ctrl-V` na dokładnie podanej konfiguracji i u mnie działa poprawnie - ale może być interakcja z jakimiś innymi komponentami.

**Comment by Ceiwark** [comment]
Po wyczyszczeniu cache pojawiła się podobny problem (załącznik).
Być może jest to interakcja, ale z tego co wiem w grupie wystąpiły podobne problemy dla innych przeglądarek - być może też zgłoszą przez githuba, będzie większa próba :)



      Od: Bogumił Kamiński <notifications@github.com>
 Do: SilverDecisions/SilverDecisions <SilverDecisions@noreply.github.com> 
DW: Ceiwark <ceiwark@yahoo.pl>; Mention <mention@noreply.github.com>
 Wysłane: 15:15 sobota, 2017-5-13
 Temat: Re: [SilverDecisions/SilverDecisions] Problem with paste (ctrl+v) (#123)
   
@Ceiwark Czy po naciśnięciu Ctrl-F5 (to powinno wyczyścić cache przeglądarki) błąd ciągle występuje.Przetestowałem Ctrl-V na dokładnie podanej konfiguracji i u mnie działa poprawnie - ale może być interakcja z jakimiś innymi komponentami.—

**Comment by bkamins** [comment]
@mwasiluk The reported problems are with master release.

**Comment by pszufe** [comment]
@mwasiluk I managed to replicate the bug on Windows 10 + Firefox 53.0.2.
The problem exists only when "Manual" tree layout is selected. Switching to "Cluster" or "Tree" layout mitigates the problem. Hence it seems to be some tree refreshing issue when a copy-paste operation is made under the "Manual" layout.

**Comment by bkamins** [comment]
@Ceiwark @pszufe Could you please check on `bogumilkaminski.pl/sddev/` if the problem is fixed.

**Comment by Ceiwark** [comment]
I confirm in the above location the problem has been resolved

**Comment by bkamins** [comment]
Thank you!
