### ISSUE TITLE
Leaguetable on Safari/OSx

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#124]
@mwasiluk below you have a link to error report from Safari/OSx that @michaljakubczyk gets when trying to test League Tble.
[lterror.txt](https://github.com/SilverDecisions/SilverDecisions/files/999307/lterror.txt)

**Comment by bkamins** [comment]
@michaljakubczyk do we still get this error?

**Comment by mwasiluk** [comment]
I'm testing this now on osx sierra on virtualbox, and it's working (at least for simple trees) and there are no errors in the safari console,  but the plot legend is missing.
![sd-osx-sierra](https://cloud.githubusercontent.com/assets/1236142/26654740/352ad39a-4658-11e7-874b-ad40c2b704f8.PNG)

**Comment by michaljakubczyk** [comment]
yes :(

**Comment by mwasiluk** [comment]
which version of os x / safari?

**Comment by mwasiluk** [comment]
I've tested it it on Safari version 10.0 (12602.1.50.0.10)

**Comment by michaljakubczyk** [comment]
I used Safari 10.1 (12603.1.30.0.34)

However, league tables work on Mac on Firefox 53.0.3 (64 bity)

**Comment by bkamins** [comment]
@mwasiluk we should look at it pretty soon - and either fix it or determine on which browser/OS combinations it fails.

**Comment by mwasiluk** [comment]
I  have a problem with reproducing this issue on virtual box

**Comment by bkamins** [comment]
@mwasiluk please discuss it with @michaljakubczyk tomorrow in the morning.

**Comment by pszufe** [comment]
done.
