### ISSUE TITLE
Copy-paste failure

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#125]
A report from user:
```
Przy próbie kopiowania części drzewa (od węzła decyzyjnego),
część ta się kasuje, natomiast po wklejeniu wszystkie etykiety znikają.
```
I will try to get more details and then we can move forward with the issue.

**Comment by bkamins** [comment]
@mwasiluk any clue about the reason. If not I will close it as I am unable to reproduce it.

**Comment by mwasiluk** [comment]
I cannot reproduce it. Maybe it's browser related?
