### ISSUE TITLE
Labels/Etykiety

### ISSUE THREAD

**Issue by ltomasMBA** [SilverDecisions/SilverDecisions#126]
W polskiej wersji językowej programu, użycie litery "ż" w opisie krawędzi automatycznie powoduje kasowanie węzła, do którego prowadzi ta krawędź.

**Comment by bkamins** [comment]
Nie jestem w stanie reprodukować tego problemu (u mnie nie kasuje). Pracuję na Chrome+Windows 10.
Na jakiej przeglądarce i systemie operacyjnym ten problem wystąpił?

**Comment by ltomasMBA** [comment]
Problem wystąpił firefox.
Nie wiem jak to się stało, ale 5 minut temu problem był – sprawdzałam dwa razy. W tej chwili jest ok.
Przepraszam za kłopot.

**Comment by bkamins** [comment]
Nie ma problemu. Dziękujemy za sygnał 👍 . Sprawdzimy i tak.

**Comment by KarolKosMBAVI** [comment]
oj,, ktoś słabo przetestował problem  :)

nie chodzi o literkę "ż"  ale o kombinacje klawiszy Prawy Alt + Z , która jest interpretowana dokładnie tak samo jak CTRL+ Z .

wiec kiedy zaraz po dodaniu noda wpisujemy "ż" w etykietę mamy efekt jak opisany w pierwszym poście , ale kiedy zrobimy klika ruchów , pododajemy  nody , opiszemy , i wtedy w dowolnym miejscu wciśniemy Prawy Alt + Z , program po prostu cofa nasze kroki.

co ciekawe wpisanie "ż" z klawiatury ekranowej daje ten sam efekt

u mnie problem występuje na FF  ESR 45.5.0 , windows 8.1

kiedy sie tak nie dzieje ? 
.., ano w momencie kiedy język klawiatury zmienimy np na English , wtedy kombinacja 
klawiszy Prawy Alt + Z otwiera na menu "zakładki" w przegladarce FF.

to taki mój wkład.
coś jeszcze mam sprawdzić ? :)

**Comment by ltomasMBA** [comment]
Tak, też pomyślałam, że chodzi o kombinacje klawiszy.
Coś się dzieje też przy literze „ć”, ale nie zabrakło mi czasu na prześledzenie tematu

**Comment by bkamins** [comment]
Super analiza. Dziękujemy.
Mamy wyzwanie takie, że utrzymujemy FF/Chrome/Edge/IE na Linux/OSx/różnych wersjach Windowsa.
To zachowanie, o którym piszesz, teoretycznie mamy obsłużone w kodzie JavaScript, ale widocznie FF na Win8.1 jego nie łapie.

**Comment by KarolKosMBAVI** [comment]
litera "ć" ..
owszem dzieje się , ale jak przeczytacie poniżej , zachowuje sie jak zdefiniowany skrót klawiszowy .. 
czy tak jest wedle zamierzeń autorów .. ?

kombinacja klawiszy Prawy Alt + C powoduje wstawianie węzła losowego w aktywnym miejscu. 
czyli działa jako komenda która mamy pod Prawym przyciskiem myszy : "dodaj węzeł losowy"

jeśli zaznaczymy węzeł decyzyjny lub losowy i wciśniemy  Prawy Alt + C zostanie dorysowany kolejny węzeł losowy. czyli "dodaj węzeł losowy"

kiedy jesteśmy na węźle końcowym i wciśniemy  Prawy Alt + C nic się nie dzieje.

kiedy zaznaczymy strzałkę łącząca węzły  i wciśniemy  Prawy Alt + C węzeł losowy zostanie dorysowany "w poziomie" jako kolejny węzeł . czyli działa jako komenda która mamy pod Prawym przyciskiem myszy : "wstrzyknij węzeł losowy"

kiedy jesteśmy w polu do opisania etykiety i wciśniemy  Prawy Alt + C zostanie dorysowany kolejny węzeł decyzyjny oraz otrzymamy literę "ć" za każde naciśnięcie w opisie etykiety. 

na razie tyle ..

**Comment by ltomasMBA** [comment]
To ja dorzucam jeszcze Windows10 do puli

**Comment by bkamins** [comment]
@ltomasMBA @KarolKosMBAVI 
Hopefully :), it should be fixed now. Could you please have a look at development version http://bogumilkaminski.pl/sddev/SilverDecisions.html

**Comment by bkamins** [comment]
@pszufe: could you please check if it works OK on dev now?

**Comment by pszufe** [comment]
I have checked on dev and now it works correctly:
- when a node is only selected (r-Alt+C inserts a chance node)
- when node label editing is selected Alt-C inserts the Polish c-acute "ć" character but new chance node is not added -> that is the desired behavior. 
Hence I can confirm that it is working (compared to the production version where I easily managed to replicate the wrong behavior)

Tested on Chrome v.58 and Firefox v.53 on the current Windows 10 version.

**Comment by bkamins** [comment]
Thank you!
