### ISSUE TITLE
MCDM: league table and plot fixes

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#127]
Highlighting of the policies in league table is slightly wrong. For example, consider a simple tree with just two simple decisions: effect=cost=1, effect=cost=2, and take “minimum range for WTP”=0.5. Both policies should be highlighted in the league table (as both may be optimal for some WTP from the range). Currently only the (2,2) policy is highlighted. It is correctly specified in the overleaf document (start highlighting from the policy with the largest ICER that is still <= minimum range for WTP)
 
Policy # | Policy | Effect | Cost | Comment
-|-|-|-|-
1 | :1 | 1 | 1 | ICER=0
2 | :2 | 2 | 2 | ICER=1

Also then plot is incorrectly drawn (@michaljakubczyk: how in general we should show plot when we define ranges of min-max WTP?)
 
Can we additionally mark in the plot the policies optimal for the default WTP value? (larger dot? brighter green?)

**Comment by bkamins** [comment]
Additional requirements (@pszufe please comment if I have missed anything):
1. add arrow showing direction of optimization (gradient: https://en.wikipedia.org/wiki/Gradient)
2. can we shade dominated region?
3. make dots on a plot a bit bigger
4. mark dot for optimal policy for default WTP in some way
5. in general improve look-and-feel of a graph (@pszufe please provide the recommendations :))
6. Link table and graph: mouse over row should higlight point, mouse over point should highlight row

**Comment by pszufe** [comment]
7. Add a legend to the graph (for dot colors and the dominated region)

Ad.1- @bkamins - I would consider just a single arrow for each maybe of a red color. Additionally we can consider marking the ideal point on the graph (e.g. top-right corner for max-max or bottom-right for max-min etc)

**Comment by bkamins** [comment]
Ad. 1 - I am indifferent. This a requirement brought by you from Dublin. Please choose what you feel most suitable. In what I have written I wanted a single arrow not a vector field.

**Comment by pszufe** [comment]
Ad .1. Yes, single arrow. This is not requirement by ROUTE-TO-PA pilots, but for sure it will increase readibility for less experienced users (or less mathematic fluent citizens...)

**Comment by bkamins** [comment]
Everything seems OK.
@pszufe do "gradient arrows" look as you wanted.
@mwasiluk no matter how "gradient arrows" should be drawn I would recommend to draw them with gray color and in the background (i.e. when there is a dot in the place of the arrow it should be over the arrow).

**Comment by pszufe** [comment]
I really like it :-) Minor comments:
1. The line spacing between cost and effect for terminal nodes should be 2px bigger
(it's 2px bigger in all other places)
2. The criterion names are not being saved to the JSON file (try changing criterion names, saving & reloading)
3. We need to add explanation to the legend (@bkamins comment on those names):
  grey rectangle - dominated region
  -->  - desired value for a criteria (improvement direction)

**Comment by bkamins** [comment]
arrows indicate improvement direction
grey area highlights dominated region

additionally @mwasiluk there is this issue with black points (they appeared on wrong JSON, but they might pop up in the future) - they are currently undocumented; could you pls. comment on them?

**Comment by mwasiluk** [comment]
@bkamins From overleaf specification:
> Dominated policies are market with red. Extended-dominated policies are marked with orange. Highlighted policies are marked with green. **The remaining policies are marked with black**.

Dot colors are configurable in settings

**Comment by bkamins** [comment]
OK

**Comment by bkamins** [comment]
OK
