### ISSUE TITLE
Graficzne zmiany w trybie Manual (layout)

### ISSUE THREAD

**Issue by pppwieczor** [SilverDecisions/SilverDecisions#130]
Przy pracy w trybie Manual (layout) podczas kopiowani, system zmienia wielkość węzłów. 
![blad wklejania](https://cloud.githubusercontent.com/assets/28774441/26189017/c6788b8c-3ba2-11e7-9596-7af48f4cf5f2.png)

**Comment by bkamins** [comment]
@pppwieczor Bardzo proszę sprawdzić, czy na stronie http://bogumilkaminski.pl/sddev/ też problem występuje (jest tam wersja rozwojowa aplikacji, w której problem powinien być rozwiązany). Proszę tylko o naciśnięcie <kbd>Ctrl-F5</kbd> po otworzeniu aplikacji SilverDecisions, żeby się przeładowała.

Jeśli problem nie występuje wtedy to proszę o potwierdzenie.
Jeśli występuje nadal to bardzo proszę o podanie na jakiej przeglądarce i pod jaką wersją systemu operacyjnego występuje ten błąd.

**Comment by pppwieczor** [comment]
Witam,

 

Tak, problem nie występuje. Super. Dziękuję.

 




Pozdrawiam / Best Regards

 

Paweł Wieczorek

Sales Director

 

tel.    +48 48 368 90 77

kom. +48 606 436 936

fax.   +48 48 368 90 10

Skype: pawel_trend_glass

TREND GLASS sp. z o. o. 

ul. Zubrzyckiego 11, 26-600 Radom 

 

NIP: 948-23-04-802   REGON: 672911706   KRS: 0000164723 

Sąd Rejonowy w Warszawie, XIV Wydział Gospodarczy Krajowego

Rejestru Sądowego  kapitał zakładowy: 7 155 000 PLN

 

Visit our website:  <http://www.trendglass.pl/> www.trendglass.pl

**Comment by bkamins** [comment]
Dziękujemy!
