### ISSUE TITLE
Flipping trees - not working

### ISSUE THREAD

**Issue by MarcelLee** [SilverDecisions/SilverDecisions#132]
option is disabled, when named edges are different order on two chance nodes
![screen](https://cloud.githubusercontent.com/assets/3586414/26256155/56d499ae-3cbc-11e7-9194-c0d659ae39c0.jpeg)

`{
  "SilverDecisions": "0.7.0",
  "buildTimestamp": 1492719501046,
  "savetime": "2017-05-19T15:53:52.970Z",
  "lng": "pl",
  "rule": "expected-value-maximization",
  "title": "",
  "description": "",
  "format": {
    "locales": "en",
    "payoff": {
      "style": "currency",
      "currency": "USD",
      "currencyDisplay": "symbol",
      "minimumFractionDigits": 0,
      "maximumFractionDigits": 2,
      "useGrouping": true
    },
    "probability": {
      "style": "decimal",
      "minimumFractionDigits": 2,
      "maximumFractionDigits": 3,
      "useGrouping": true
    }
  },
  "treeDesigner": {
    "margin": {
      "left": 25,
      "right": 25,
      "top": 25,
      "bottom": 25
    },
    "layout": {
      "type": "tree",
      "nodeSize": 40,
      "limitNodePositioning": true,
      "gridHeight": 75,
      "gridWidth": 150,
      "edgeSlantWidthMax": 20
    },
    "fontFamily": "sans-serif",
    "fontSize": "12px",
    "fontWeight": "normal",
    "fontStyle": "normal",
    "node": {
      "strokeWidth": "1px",
      "optimal": {
        "stroke": "#006f00",
        "strokeWidth": "1.5px"
      },
      "label": {
        "fontSize": "1em",
        "color": "black"
      },
      "payoff": {
        "fontSize": "1em",
        "color": "black",
        "negativeColor": "#b60000"
      },
      "decision": {
        "fill": "#ff7777",
        "stroke": "#660000",
        "selected": {
          "fill": "#aa3333"
        }
      },
      "chance": {
        "fill": "#ffff44",
        "stroke": "#666600",
        "selected": {
          "fill": "#aaaa00"
        }
      },
      "terminal": {
        "fill": "#44ff44",
        "stroke": "black",
        "selected": {
          "fill": "#00aa00"
        },
        "payoff": {
          "fontSize": "1em",
          "color": "black",
          "negativeColor": "#b60000"
        }
      }
    },
    "edge": {
      "stroke": "#424242",
      "strokeWidth": "1.5",
      "optimal": {
        "stroke": "#006f00",
        "strokeWidth": "2.4"
      },
      "selected": {
        "stroke": "#045ad1",
        "strokeWidth": "3.5"
      },
      "label": {
        "fontSize": "1em",
        "color": "back"
      },
      "payoff": {
        "fontSize": "1em",
        "color": "black",
        "negativeColor": "#b60000"
      }
    },
    "probability": {
      "fontSize": "1em",
      "color": "#0000d7"
    },
    "title": {
      "fontSize": "16px",
      "fontWeight": "bold",
      "fontStyle": "normal",
      "color": "#000000",
      "margin": {
        "top": 15,
        "bottom": 10
      }
    },
    "description": {
      "show": true,
      "fontSize": "12px",
      "fontWeight": "bold",
      "fontStyle": "normal",
      "color": "#000000",
      "margin": {
        "top": 5,
        "bottom": 10
      }
    },
    "disableAnimations": false,
    "forceFullEdgeRedraw": false,
    "hideLabels": false,
    "hidePayoffs": false,
    "hideProbabilities": false,
    "raw": false
  },
  "data": {
    "code": "",
    "expressionScope": {},
    "trees": [
      {
        "computed": {
          "expected-value-maximization": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          },
          "expected-value-minimization": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          },
          "maxi-min": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          },
          "maxi-max": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          },
          "mini-min": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          },
          "mini-max": {
            "childrenPayoff": "0",
            "payoff": "0",
            "optimal": true
          }
        },
        "childEdges": [
          {
            "computed": {
              "payoff": "0",
              "probability": "999/1000",
              "expected-value-maximization": {
                "probability": "999/1000",
                "optimal": true
              },
              "expected-value-minimization": {
                "probability": "999/1000",
                "optimal": true
              },
              "maxi-min": {
                "probability": 0.5,
                "optimal": true
              },
              "maxi-max": {
                "probability": 0.5,
                "optimal": true
              },
              "mini-min": {
                "probability": 0.5,
                "optimal": true
              },
              "mini-max": {
                "probability": 0.5,
                "optimal": true
              }
            },
            "name": "trz",
            "probability": "#",
            "payoff": 0,
            "childNode": {
              "computed": {
                "expected-value-maximization": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "expected-value-minimization": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "maxi-min": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "maxi-max": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "mini-min": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "mini-max": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                }
              },
              "childEdges": [
                {
                  "computed": {
                    "payoff": "0",
                    "probability": "19/20",
                    "expected-value-maximization": {
                      "probability": "19/20",
                      "optimal": true
                    },
                    "expected-value-minimization": {
                      "probability": "19/20",
                      "optimal": true
                    },
                    "maxi-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "maxi-max": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-max": {
                      "probability": 0.5,
                      "optimal": true
                    }
                  },
                  "name": "0",
                  "probability": "0.95",
                  "payoff": 0,
                  "childNode": {
                    "computed": {
                      "expected-value-maximization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "18981/20000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "expected-value-minimization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "18981/20000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      }
                    },
                    "childEdges": [],
                    "name": "",
                    "code": "",
                    "expressionScope": {},
                    "location": {
                      "x": 320,
                      "y": 20
                    },
                    "type": "terminal"
                  }
                },
                {
                  "computed": {
                    "payoff": "0",
                    "probability": "1/20",
                    "expected-value-maximization": {
                      "probability": "1/20",
                      "optimal": true
                    },
                    "expected-value-minimization": {
                      "probability": "1/20",
                      "optimal": true
                    },
                    "maxi-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "maxi-max": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-max": {
                      "probability": 0.5,
                      "optimal": true
                    }
                  },
                  "name": "1",
                  "probability": "#",
                  "payoff": 0,
                  "childNode": {
                    "computed": {
                      "expected-value-maximization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "999/20000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "expected-value-minimization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "999/20000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      }
                    },
                    "childEdges": [],
                    "name": "",
                    "code": "",
                    "expressionScope": {},
                    "location": {
                      "x": 320,
                      "y": 95
                    },
                    "type": "terminal"
                  }
                }
              ],
              "name": "wynik",
              "code": "",
              "expressionScope": {},
              "location": {
                "x": 170,
                "y": 57.5
              },
              "type": "chance"
            }
          },
          {
            "computed": {
              "payoff": "0",
              "probability": "1/1000",
              "expected-value-maximization": {
                "probability": "1/1000",
                "optimal": true
              },
              "expected-value-minimization": {
                "probability": "1/1000",
                "optimal": true
              },
              "maxi-min": {
                "probability": 0.5,
                "optimal": true
              },
              "maxi-max": {
                "probability": 0.5,
                "optimal": true
              },
              "mini-min": {
                "probability": 0.5,
                "optimal": true
              },
              "mini-max": {
                "probability": 0.5,
                "optimal": true
              }
            },
            "name": "pij",
            "probability": "0.001",
            "payoff": 0,
            "childNode": {
              "computed": {
                "expected-value-maximization": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "expected-value-minimization": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "maxi-min": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "maxi-max": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "mini-min": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                },
                "mini-max": {
                  "childrenPayoff": "0",
                  "payoff": "0",
                  "optimal": true
                }
              },
              "childEdges": [
                {
                  "computed": {
                    "payoff": "0",
                    "probability": "1",
                    "expected-value-maximization": {
                      "probability": "1",
                      "optimal": true
                    },
                    "expected-value-minimization": {
                      "probability": "1",
                      "optimal": true
                    },
                    "maxi-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "maxi-max": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-max": {
                      "probability": 0.5,
                      "optimal": true
                    }
                  },
                  "name": "1",
                  "probability": "1",
                  "payoff": 0,
                  "childNode": {
                    "computed": {
                      "expected-value-maximization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/1000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "expected-value-minimization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/1000",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      }
                    },
                    "childEdges": [],
                    "name": "",
                    "code": "",
                    "expressionScope": {},
                    "location": {
                      "x": 320,
                      "y": 185
                    },
                    "type": "terminal"
                  }
                },
                {
                  "computed": {
                    "payoff": "0",
                    "probability": "0",
                    "expected-value-maximization": {
                      "probability": "0",
                      "optimal": true
                    },
                    "expected-value-minimization": {
                      "probability": "0",
                      "optimal": true
                    },
                    "maxi-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "maxi-max": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-min": {
                      "probability": 0.5,
                      "optimal": true
                    },
                    "mini-max": {
                      "probability": 0.5,
                      "optimal": true
                    }
                  },
                  "name": "0",
                  "probability": "#",
                  "payoff": 0,
                  "childNode": {
                    "computed": {
                      "expected-value-maximization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "0",
                        "payoff": "0",
                        "optimal": true
                      },
                      "expected-value-minimization": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "0",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "maxi-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-min": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      },
                      "mini-max": {
                        "aggregatedPayoff": "0",
                        "probabilityToEnter": "1/4",
                        "payoff": "0",
                        "optimal": true
                      }
                    },
                    "childEdges": [],
                    "name": "",
                    "code": "",
                    "expressionScope": {},
                    "location": {
                      "x": 320,
                      "y": 260
                    },
                    "type": "terminal"
                  }
                }
              ],
              "name": "wynik",
              "code": "",
              "expressionScope": {},
              "location": {
                "x": 170,
                "y": 222.5
              },
              "type": "chance"
            }
          }
        ],
        "name": "jest",
        "code": "",
        "expressionScope": {},
        "location": {
          "x": 20,
          "y": 140
        },
        "type": "chance"
      }
    ],
    "texts": []
  },
  "sensitivityAnalysis": {}
}`

**Comment by pszufe** [comment]
Dear MarcLee,

The tree flipping algorithm requires the labels of all child edges to have the same names and be in the same order. 
On your graph the labels of possible results are (0, 1) for the upper chance node and (1, 0) for the lower chance node. Simply change the order of your terminal nodes on the lower chance node. The simplest way to do it is to change to "manual" layout and change the order of the terminal nodes. 
Please let us know if it worked for you.
