### ISSUE TITLE
Propagation of variable values

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#136]
Sometimes defined variables do not propagate down the tree (see e-mail from @michaljakubczyk). Recompute fixes the issue, but they should propagate without recompute.

**Comment by bkamins** [comment]
@michaljakubczyk I have updated dev version of SD that should solve this. Could you please check and let me know.

**Comment by bkamins** [comment]
@michaljakubczyk what is the status of this issue?

**Comment by michaljakubczyk** [comment]
seems not to be working :(
here's what I do:
1. I create a tree: a chance node, leading to two chance nodes, each
leading to two terminal nodes
2. I name two first branches as x, y
3. I name the branches in two deeper pair of branches as a, b
4. I flip the whole tree
5. I create (global scope) p parameter, p=0.6
6. I replace the probability in the first chance node in the upper branch
with p; I change the other one to #
7. It is not updated; recalculate does not help
(perhaps the flipping does something bad to the scopes?)

cheers,
michal

**Comment by bkamins** [comment]
The probability propagates on my laptop, but payoff is corrupted:
![image](https://cloud.githubusercontent.com/assets/6187170/26682224/f9e1d0f8-46df-11e7-8385-131debbd55bf.png)

@mwasiluk what is this `undefined` in payoff?

**Comment by bkamins** [comment]
In general `flip subtree` is now broken - even without variables.

**Comment by mwasiluk** [comment]
I have forgotten to update flip operation with mcdm. We need more regression tests to catch this kind of issues.

**Comment by bkamins** [comment]
@mwasiluk weight flipping works OK, but payoff flipping is broken.
Take the following tree:
[test.txt](https://github.com/SilverDecisions/SilverDecisions/files/1045259/test.txt)
and flip it twice (which should get you back to the start).
Also you can see that after one flip aggregated payoff is wrong.

**Comment by bkamins** [comment]
OK
