### ISSUE TITLE
MCDM: identification of dominated strategies

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#137]
Per email from @michaljakubczyk current functionality sometimes produces wrong results. Policy 6 is handled in a wrong way.
![image](https://cloud.githubusercontent.com/assets/6187170/26519482/e94772e2-42c1-11e7-9f0d-e9c0ed8e0cab.png)

**Comment by bkamins** [comment]
@mwasiluk This fix introduces a regression error, when upper bound is changed to `Infinity`:
![image](https://cloud.githubusercontent.com/assets/6187170/26521183/ddb738f6-42e2-11e7-83b1-741c9480e4cd.png)

**Comment by bkamins** [comment]
Additionally SD should check if `lower bound<upper bound` and indicate an error then, otherwise nonsense results can be produced.

**Comment by bkamins** [comment]
All seems OK now. @michaljakubczyk please double check.
One small UI improvement (in three fields where weight is provided):
* incorrect input in sometimes makes red underline (e.g. `-1`), but sometimes not e.g. `0fsdfsd1`; in the latter case it should also be underlined and `show league table` should be disabled; also flipping should be disabled, because after it is clicked two or three times it replaces the wrong value by `0`
* if lower bound>upper bound I would also disable flip button and underline both lower and upper bounds with red - as in other places in the application
* it is impossible to input variable name like `Infinity_blah`, because it is trimmed to `Infinity` - it is OK, but please confirm that it is intended, and not a side effect.

In general: handling of improper values could be tidied up a bit.

**Comment by bkamins** [comment]
Still we have a slight problem with gray area when lower and upper bounds are extreme:
![image](https://cloud.githubusercontent.com/assets/6187170/26604865/04b40eec-458c-11e7-9693-2a8bd6cc7ec0.png)

**Comment by bkamins** [comment]
@michaljakubczyk in implementation we assume that weight larger than `9'999'999` is the same as infinity for plotting gray area.
@mwasiluk I am accepting this for `0.8` to move forward but we should fix it properly in the future, so I keep the issue open as hotfix enchancement.

**Comment by michaljakubczyk** [comment]
looks fine to me!

**Comment by bkamins** [comment]
Have you tested huge weights (beyond `9'999'999`).

**Comment by bkamins** [comment]
Works OK
