### ISSUE TITLE
Improve regression testing for SD

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#139]
Currently we have the following testing procedure:
* limited automatic tests located in `test` directory
* release testing procedure described in https://github.com/SilverDecisions/SilverDecisions/wiki/Developer's-guide

We have reached the level of complexity of SD that we need better unit and regression testing.

@pszufe please take the lead in defining the improved test workflow for SD. I will arrange a meeting for beginning of June to discuss the recommendations and implement them in summer. Probably we will have automated and manual tests.

@mwasiluk will implement what we decide is needed. Rest of the team @michaljakubczyk etc. - will develop test cases.

**Comment by mwasiluk** [comment]
First of all we need more automated unit tests, e.g. for jobs (like sensitivity analysis, league table) and for all types of operations like tree flipping, node injection etc.

**Comment by bkamins** [comment]
yes, and we need to define some automated testing API.

**Comment by pszufe** [comment]
The initial recommendation: Serenity on top of Selenium and Webdriver
http://thucydides.info/docs/serenity-staging/
all is Open Source

**Comment by bkamins** [comment]
Great. The action plan is that during June @pszufe should discuss with @mwasiluk the tools, process, roles and responsibilities in testing (of with automated testing is a part). We will start implementing it in July.

**Comment by bkamins** [comment]
The decision is that in the first step we will develop unit tests to improve test code coverage.
We can use standard GitHub integrations to https://coveralls.io or https://codecov.io or both.

**Comment by pszufe** [comment]
@mwasiluk  can you add a short information to the developer documentation on how to use regression testing with SD so we can close this issue?

**Comment by pszufe** [comment]
done and documented at the Developer's Guide:
https://github.com/SilverDecisions/SilverDecisions/wiki/Developer's-guide
