### ISSUE TITLE
ability to merge branches

### ISSUE THREAD

**Issue by skyboyer** [SilverDecisions/SilverDecisions#140]
There are some cases when two different decision branches should be merged: say several flows has common part or even making decision should result in the same action(but one of alternatives need additional action or decision is made).

Currently it cannot be implemented explicitly. Common parts have be just copied between different branches.

**Comment by bkamins** [comment]
@skyboyer Thank you for your comment. Unfortunately this is the restriction that we have to have if we want other functionalities of SilverDecisions to work.
Most importantly we allow users to define variables in nodes. If one node had two parents and if in those two parents a different value for the same variable would be defined then it would be problematic which value should the variable have in child node.
