### ISSUE TITLE
Mobile Device Support: Right Click Function.

### ISSUE THREAD

**Issue by olymrtnz** [SilverDecisions/SilverDecisions#141]
Add a function to support mobile device's right click. It can be done by long pressing

**Comment by bkamins** [comment]
What OS and browser are you using?
This is exactly what we have implemented.
It should work under Chrome on Android.

**Comment by olymrtnz** [comment]
Hello,

Thanks for the reply! I've used Safari, Chrome and even Firefox on the
mobile device, but none seem to work. I've tried long pressing but the menu
does not appear, but works perfectly on desktop.

Kind regards,.
Oliverio

**Comment by bkamins** [comment]
But please tell me what OS are you on. We do not support OSx, but on Android it should work (and we will investigate it).

**Comment by olymrtnz** [comment]
Okay, could you point me to the code where support from Android chrome was added please:)

**Comment by bkamins** [comment]
https://github.com/SilverDecisions/SilverDecisions/blob/9383777f3f324bca04c314987a4fff8ff3791ccc/src/tree-designer/tree-designer.js
`Hammer.press` actions; @mwasiluk - please confirm if there is something more to comment on here as you have implemented it.

**Comment by mwasiluk** [comment]
Mobile support is implemented using [Hammer.js](https://hammerjs.github.io/). 

It works on my android phone.

For example:

Here is svg press and pinch support (disabling brush)
https://github.com/SilverDecisions/sd-tree-designer/blob/43eaeacb0cee413af546e811ebce51ca85b3b280/src/tree-designer.js#L280

Here is support for node press:
https://github.com/SilverDecisions/sd-tree-designer/blob/43eaeacb0cee413af546e811ebce51ca85b3b280/src/tree-designer.js#L735

Sorry for the late response.
I hope it helps.

**Comment by mwasiluk** [comment]
I'm closing it for now, but please let us know if the problem persists.
