### ISSUE TITLE
URL does not work when JSON file is in my server

### ISSUE THREAD

**Issue by fjdiez** [SilverDecisions/SilverDecisions#145]
I created a tree with SilverDecisions and put it in my server, but it does not work: the icon keeps moving for ever, instead of showing the tree:
http://www.silverdecisions.pl/SilverDecisions.html?LOAD_SD_TREE_JSON=http://www.cisiad.uned.es/misc/decisiontree-decide-test.json

Thinking the problem might be in my tree, I downloaded a file from SilverDecisions's Gallery, but it does not work either: 
http://silverdecisions.pl/SilverDecisions.html?LOAD_SD_TREE_JSON=http://www.cisiad.uned.es/misc/temp.json

Nevertheless, the files themselves are accessible and seem to be correct:
http://www.cisiad.uned.es/misc/decisiontree-decide-test.json
http://www.cisiad.uned.es/misc/temp.json

**Comment by pszufe** [comment]
Hi fjdiez,

By default a web browser does not allow to open files from a different server.
Hence, the error you get is probably:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource

First option for you is to checkout SilverDecisions and to copy SilverDecisions.html along other files to the same server where you are hosting the JSON files and then use your web copy of SilverDecisions. 

Second option (not recommended) is to disable Cross-Origin check in your web-browser. 

Third option: I will check with @bkamins  if we can add  Access-Control-Allow-Origin: *  header to the SilverDecisions web site - in that case it would solve your problem. 

Thank you for using SilverDecisions,
Przemyslaw

**Comment by bkamins** [comment]
@pszufe I believe that the issue is that @fjdiez uses *http* not *https* protocol.
@fjdiez - could you please check if SilverDecision works if you serve your files via *https* (this is the way we serve it from gallery)?

**Comment by bkamins** [comment]
@fjdiez After investigation of the problem we will have to reconfigure hosting of SilverDecisions. We will let you know when it is done.

**Comment by pszufe** [comment]
@fjdiez seems all you need to do is to add a `.htaccess` file to the folder that you are hosting your `*.json` files. The contents of the `.htaccess` should be following:

`
Header set Access-Control-Allow-Origin "*"
`

Please note it will only work when your web-server administrator has enabled Header module. If not they should run on their server `sudo a2enmod headers && sudo service apache2 restart` (the exact command might differ for less obvious Apache configurations). 

Note for future readers: 
- this is an explanation for Apache web server only, for other servers check your reference manual. You can easily check your web server type with command such as 
`curl -D - http://www.cisiad.uned.es | more`

**Comment by bkamins** [comment]
@fjdiez We have tested it and it works on our tests. Does it solve your issue?
(please note that CORS policy will not allow SilverDecisions to access your file unless you tell your web serwer that this is OK)

**Comment by fjdiez** [comment]
Dear SilverDecision developers,

I thank you for your efforts to solve this issue. When our web administrator is available, I will ask him to make the changes you propose and I will let you know about the result. 

Best wishes
   Javier
