### ISSUE TITLE
Error when opening a tree with hidden probabilities and currency symbol

### ISSUE THREAD

**Issue by michaljakubczyk** [SilverDecisions/SilverDecisions#146]
What I did:
1. start with new window
2. add a decision node
3. add a single terminal node
4. open Settings
5. set pay-off 1 to decimal
6. select other to hide probabilities
7. close Settings
8. save the file
9. try to open the file - failed ("Error while drawing diagram!")

(Windows, Firefox)

**Comment by bkamins** [comment]
under Windows/Chrome everything was OK.
But the same JSON under FF does not load.
I attach the file [load_error.txt](https://github.com/SilverDecisions/SilverDecisions/files/1151013/load_error.txt).

**Comment by bkamins** [comment]
@mwasiluk The problem persists. I have created a file under Chrome and it does not open under FF.

**Comment by mwasiluk** [comment]
Are you sure? Can you send me this savefile?  
If you have tested it here http://bogumilkaminski.pl/sddev/SilverDecisions.html it looks like the app wasn't updated (build 1499864254225 vs 1500502714910)

**Comment by bkamins** [comment]
OK
