### ISSUE TITLE
N-way sensitivity display

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#148]
@mwasiluk I have two questions concerning N-way display in tables given below. First please answer if it is fixable or we have to live with it.

1. why "Table Barchart" plot is plotted from 0 to max value? I would prefer it plotted from min to max value (problems: a) if there are negative payoffs they are plotted as 0 as they are truncated, b) if there are payoffs e.g. in range 1000 to 1010 every bar is ~ the same height using all space)
2. With Hetatmap and its variants (Row and Column) I have the following example plot as below. Something is wrong with it - it should not be all red:
![image](https://user-images.githubusercontent.com/6187170/28503291-1ac19892-7004-11e7-82b7-8115bcd338ab.png)

**Comment by mwasiluk** [comment]
I have corrected heatmap coloring, but it seems that bar chart can be only plotted from 0 to max value. There is no customization point provided for changing this behaviour
https://github.com/nicolaskruchten/pivottable/blob/master/pivot.coffee#L1090

**Comment by bkamins** [comment]
now we have the following scaling:
* negative values: blue to white
* positive values: white to red

This means that if we have only positive values they are plotted from white to red.
If we have negative and positive they are plotted blue-white-red.

I do not have strong preference but I want this decision to be explicit.

@michaljakubczyk is this what we want (or we want to always have blue-white-red colormap)?

**Comment by bkamins** [comment]
The decision is:
* make heatmap colors aways use full colormap (0 should not be treated in a special way)
* the colormap used should be *plasma* from https://matplotlib.org/users/colormaps.html

@mwasiluk is this possible and relatively simple? If not we can leave it as is. Please comment.

**Comment by mwasiluk** [comment]
D3 has builtin support for some color scales, plasma included. 
https://github.com/d3/d3-scale#sequential-scales

**Comment by mwasiluk** [comment]
Maybe we should select some lighter color scheme?
![screenshot from 2017-07-28 20-09-02](https://user-images.githubusercontent.com/1236142/28730560-fa6f160c-73d0-11e7-947e-238e888f697f.png)

**Comment by mwasiluk** [comment]
For comparison:

Warm
![interpolatewarm](https://user-images.githubusercontent.com/1236142/28730951-43e745f6-73d2-11e7-984e-0571f062111f.png)

Cool
![interpolatecool](https://user-images.githubusercontent.com/1236142/28731097-d4d02b50-73d2-11e7-80f9-979ea207f6e7.png)

**Comment by mwasiluk** [comment]
Previous scheme with white for the middle value, not for 0
![bwr](https://user-images.githubusercontent.com/1236142/28731421-22c19816-73d4-11e7-8606-1e7f943938f3.png)

**Comment by mwasiluk** [comment]
I have found an open issue in pivot.js with pr regarding negative values in the barchart. https://github.com/nicolaskruchten/pivottable/issues/644

**Comment by bkamins** [comment]
OK
