### ISSUE TITLE
Variable definitions - add a current variable namespace scope label

### ISSUE THREAD

**Issue by pszufe** [SilverDecisions/SilverDecisions#151]
In the "Variables" tab a user is not being informed whether edited variables are within a global or a local variable scope. This might be specially confusing when user accidentally selects or deselects a node in the tree. 

A small scope-dependent label could be a very nice improvement: 

- When editing global scope variables under the "code" label add a text "(global variable scope)".
- When editing local scope variables under the "code" label add a text ("variable scope: the selected node and below")

**Comment by bkamins** [comment]
@mwasiluk To make the naming more consistent maybe better would be:
`variables scope: global`
and
`variables scope: node and subtree`
?

**Comment by pszufe** [comment]
@bkamins - I would consider adding the word *selected* 
`variables scope: global`
and
`variables scope: selected node and subtree`

**Comment by bkamins** [comment]
@mwasiluk I have uploaded it but cannot see the change. It seems as if `docs` directory were not built.
Additionally the same labels could be shown in *code definition dialog*.

Now it has header `Variable definitions` and it could be:
* `Variable definitions: global scope`
* `Variable definitions: selected note and subtreee scope`

**Comment by bkamins** [comment]
OK
