### ISSUE TITLE
SA parameter removal

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#153]
I had two parameters in SA: R1 and R2. I have removed R1 and want to remove R2, but `-` sign on the right has disappeared:

![image](https://user-images.githubusercontent.com/6187170/29165300-8846cac4-7dc2-11e7-9bb8-c7dd4b07cb69.png)

**Comment by mwasiluk** [comment]
It's not a bug, it's intended behaviour ;)

**Comment by bkamins** [comment]
OK - now I understand.
`R2` was left due #152 and that is why I thought it was wrong :).
