### ISSUE TITLE
SA: policy preview

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#154]
In SA policy preview not whole subtree is highlighted (in green by default), but only the edges going out from decision node. See below that edges from chance node (that are optimal) are not highlighted.

![image](https://user-images.githubusercontent.com/6187170/29202398-11886c2a-7e68-11e7-90c9-223912f82cd3.png)

I thought that the whole optimal subtree should be highlighted.
@mwasiluk: if there was some idea behind highlighting only edges going out from decision node please let me know.

**Comment by mwasiluk** [comment]
It was intentional. Should be correct now.

**Comment by bkamins** [comment]
OK
