### ISSUE TITLE
wrong display of league table

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#159]
[decisiontree@2017.11.06_10.25.25.txt](https://github.com/SilverDecisions/SilverDecisions/files/1445894/decisiontree.2017.11.06_10.25.25.txt)

The attached file generates such a plot:

![image](https://user-images.githubusercontent.com/6187170/32437424-99bbdd0c-c2e7-11e7-94ed-3604d187a557.png)

which is wrong. if you flip the order of the criteria you get a correct plot:

![image](https://user-images.githubusercontent.com/6187170/32437404-82626ca2-c2e7-11e7-83cf-f3da0931f3bd.png)

**Comment by mwasiluk** [comment]
It looks like the implemented algorithm selects a wrong "recommended for default WTP"?

**Comment by bkamins** [comment]
The top plot should be identical as the bottom plot - only reflected by x=y axis.
So on top plot 4 should be optimal and thick line should not cross shaded area (as it makes no sense) - it only should touch it.

**Comment by bkamins** [comment]
it is acceptable that numbers of decisions are not consistent between plots (as it is now) as those numbers are only supporting information.

**Comment by pszufe** [comment]
tested. done.
