### ISSUE TITLE
Mac user: not able to save file with Safari

### ISSUE THREAD

**Issue by KrystianSnopko** [SilverDecisions/SilverDecisions#163]
Dear Team,
When using Safari browser on Mac for silverdecisions.pl and trying to save the work done (a decision tree for example) the site gives an error showing the script code (attached: 
<img width="457" alt="screen shot 2017-11-18 at 18 13 49" src="https://user-images.githubusercontent.com/33788315/32982965-2e28acf0-cc8d-11e7-84d7-0b3c0bf4ca29.png">
The result is that the work is gone and you need to start from scratch.
A solution for Mac users is to use Mozilla Firefox where there are no issues with saving files.
Best regards
Krystian

**Comment by pszufe** [comment]
Dear Krystian,
the code that you attached is SilverDecision's presentation of a saved file. If you save it to a *.json file you should be able to use the "Open an existing diagram" feature to load the model back to SilverDecisions.

**Comment by bkamins** [comment]
@pszufe but maybe there is some bug on Safari (we know that Safari is problematic) leading to a dump of the savefile in the browser window.

@KrystianSnopko could you please post a screenshot of the error so that we can understand better what happens?

**Comment by KrystianSnopko** [comment]
Hi there,
I have just updated to MacOS High Sierra and the issue disappeared - now I can save files through Safari.
So most probably it was a browser issue or maybe a not up to date mac version.
Thanks for your comments and help though
Best regards
Krystian

**Comment by bkamins** [comment]
OK. Closing the issue then.
