### ISSUE TITLE
Currency formatting

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#17]
1) add space after currency name (now we get e.g. PLN1000 without a space)
2) currently any three-letter code is accepted (this is OK) but add validation that only three-letter codes are accepted (now there is no validation and you can enter e.g. `1232984` there)

**Comment by annawier** [comment]
documented, but it's recommended to double check this section :)

**Comment by bkamins** [comment]
@pszufe please correct this part of documentation.
In general e.g.:
1) `uk` locale does not work and is documented as working
2) `en` locale is default and is not documented at all
3) I would recommend to put into the table three columns: country/locale code/currency as recommended combinations

and in general please read the whole text regarding locale and currency (it is spread into 3 places in the documentation) to make sure that it is proper and consistent. When you sign-off I will recheck the documentation.

**Comment by pszufe** [comment]
done.
