### ISSUE TITLE
New Feature Request: keyboard shortcuts enabled

### ISSUE THREAD

**Issue by kamilsabatowski** [SilverDecisions/SilverDecisions#184]
fajnie, gdyby można było korzystać ze skrótów klawiszowych np. delete, copy, paste, cut - wielokrotnie intuicyjnie chciałem skorzystać z takiej możliwości, ale nie dało się (Mac OS)

**Comment by mwasiluk** [comment]
https://github.com/SilverDecisions/SilverDecisions/wiki/3.-Actions-supported-by-application

Keyboard shortcuts:
Del: delete selected nodes
Ctrl-C/X: copy/cut selected nodes
Ctrl-V: paste copied nodes as a subtree of a selected node
Ctrl-Y/Z: undo/redo
Ctrl-Alt-D/C/T: add new Decision/Chance/Terminal subnode of a selected node
**On OSx, Ctrl should be used as well (and not Cmd).**

**Comment by bkamins** [comment]
Czy o to chodziło?

**Comment by kamilsabatowski** [comment]
tak, dokładnie - ale nie działa właśnie na OSx Mojave 10.14. Próbnowałem oczywiście zarówno z cmd jak i ctrl.

**Comment by bkamins** [comment]
@michaljakubczyk - to też możesz pls. sprawdzić na macOS?

**Comment by michaljakubczyk** [comment]
u mnie działają poniższe:
Del (fn-backspace): delete selected nodes
Ctrl-C/X: copy/cut selected nodes
Ctrl-V: paste copied nodes as a subtree of a selected node
Ctrl-Y/Z: undo/redo
Ctrl-Alt-D/C/T: add new Decision/Chance/Terminal subnode of a selected node

Natomiast przy kopiowaniu i wklejaniu jest czasem problem, jeśli zrobi się to zbyt szybko (tzn. zaznaczam węzeł, szybko wciskam Ctrl-C, zaznaczam inne miejsce i szybko wciskam Ctrl-V) . Wtedy czasem wkleja coś, co było w schowku wcześniej. Jakaś bezwładność zawartości schowka?

**Comment by mwasiluk** [comment]
@michaljakubczyk Czy tutaj jest coś do poprawienia? 

Co do szybkiego wciskania Ctrl-C / Ctrl-V: może przy szybkim wciskaniu przyciski ctrl +c czasami nie są wciśnięte jednocześnie?
Czy ten objaw jest tylko na Mac OS?

**Comment by michaljakubczyk** [comment]
Teraz próbowałem i wszystko działa ok.
