### ISSUE TITLE
funkcjonalność

### ISSUE THREAD

**Issue by KAHAWR** [SilverDecisions/SilverDecisions#188]
warto byłoby, aby przy podawaniu prawdopodobieństw program honorował zarówno kropki jak i przecinki:

0.1
0,1

**Comment by bkamins** [comment]
Nie damy rady tego zaimplementować, ponieważ standardowo w językach programowania `.` oznacza miejsce dziesiętne. Możemy to zmieniać jedynie w warstwie prezentacji
