### ISSUE TITLE
Presence of a function in any variable field breaks sensitivity analysis

### ISSUE THREAD

**Issue by andersonad** [SilverDecisions/SilverDecisions#189]
If there is a function (e.g. f() = 1) in any variable field in any node or globally, sensitivity analysis cannot complete.

Here is an example json displaying the issue using Ron Howard's Canonical party problem with Kim and a specified u-curve.

[decisiontree@2019.05.16_17.51.00.zip](https://github.com/SilverDecisions/SilverDecisions/files/3189343/decisiontree%402019.05.16_17.51.00.zip)

**Comment by bkamins** [comment]
@mwasiluk can you please investigate into it?

**Comment by andersonad** [comment]
Can confirm this fixes the issue for me in build.
