### ISSUE TITLE
Allow a function to be applied to the aggregation of payoff results

### ISSUE THREAD

**Issue by andersonad** [SilverDecisions/SilverDecisions#190]
At the moment after specifying monetary payoffs throughout a decision tree, it is not possible to apply a transformation of the aggregated terminal values before maximization, nor to apply a transformation to the payoff function. 

Since it is a common practice in decision analysis to encode a person's risk preferences by mapping monetary outcomes to preference probabilities and vice-versa, it would be good if one could get access to the payoff and terminal outcome aggregation variables in order to apply these mappings.

e.g. I may use the following risk curve: u(x) = 4/3*(1-(1/2)^(x/50)) for x between [0,100]. So a payout of $90 corresponds to a 0.95 preference probability, which is the value of interest when maximizing over my utility, rather than raw monetary outcomes (a risk neutral risk preference)

**Comment by bkamins** [comment]
@michaljakubczyk - could you please have a look a it on a design level so that we can have a proper specification (or a recommendation how to do it currently). Thank you.

**Comment by michaljakubczyk** [comment]
I agree it would be very useful, and I currently have to use some work-arounds for teaching. When you want to show how decision trees can be used while accounting for risk aversion (represented by a concave utility function) you need to assign all the pay-offs (transformed with the utility function) to the very last edge. This is for example done in the attached figure: the upper tree contains monetary pay-offs, the middle tree assignes the aggregated pay-offs to the edges just before the terminal nodes (the pay-offs were transformed with the log-utility, a more standard one than the one provided in the original comment). Here, the risk aversion does not change the decision (i.e. a gamble between B1 and B2)

However, notice that introducing the risk aversion may result in non-trivial changes of the decision along the tree (i.e. in subproblems). In the example provided, once we are past the 1st move (common to both alternatives), the decision switches to "A". Also, the backward induction cannot be used for finding the optimal decision.

![illustration](https://user-images.githubusercontent.com/22515038/59086043-d8b11500-8900-11e9-97fb-01b039cad8d5.png)

One way or another, from the users perspective, it would be nice to add an option of basing the decision on the transformation of the aggregate pay-offs. From the implementation perspective, it might require quite some changes.

**Comment by andersonad** [comment]
Can confirm the new feature is working in dev build and addresses the underlying problem according to the test outlined above.

**Comment by andersonad** [comment]
Sorry I took so long to close this issue. I was waiting for the changes to make it into master and didn't come back for a long while!
