### ISSUE TITLE
failure to detect extended dominance in two-criteria problems (when multiple alternatives are extended dominated)

### ISSUE THREAD

**Issue by michaljakubczyk** [SilverDecisions/SilverDecisions#200]
In the attached example, option C is extended-dominated by A and E. SilverDecisions fails to notice that (and calculates incremental ratio normally)
![tree](https://user-images.githubusercontent.com/22515038/132909721-18790bca-80fa-4768-8d52-7f69a1cf04c5.PNG)
![league](https://user-images.githubusercontent.com/22515038/132909737-af901a23-db06-4aad-8f03-4ed61ab6ba2c.PNG)

**Comment by mwasiluk** [comment]
Is this a bug in the implementation only or is there also a problem with the algorithm described here: https://www.overleaf.com/read/gjtgsvkmbnxz ?

**Comment by bkamins** [comment]
The description of the algorithm to be used did not handle this particular situation. The description has been elaborated in the document now.

**Comment by mwasiluk** [comment]
Is this the expected result ?
![image](https://user-images.githubusercontent.com/1236142/142272278-8f95983a-3bc3-47ee-965f-18e6f3fb5219.png)

**Comment by michaljakubczyk** [comment]
looks good!

**Comment by mwasiluk** [comment]
@michaljakubczyk new version can be tested here: http://wasiluk.io/SilverDecisions/

**Comment by michaljakubczyk** [comment]
I've just tested it, and it works fine. Thanks.
