### ISSUE TITLE
Tree Flipping does not work

### ISSUE THREAD

**Issue by tbarton782** [SilverDecisions/SilverDecisions#212]
When I click "Flip subtree" nothing happens.  I have tried on Chrome, Edge, and Firefox.

The only way I can get it to work is by using the previous version (1.1.0).

How do I flip using the current version?

<img width="504" alt="2022-03-18 20_33_01-Calculator" src="https://user-images.githubusercontent.com/56707093/159105165-b9d98b8c-96ab-4ec3-a6ad-9e7a3432208b.png">

**Comment by bkamins** [comment]
@mwasiluk + @pszufe could you please check it.

**Comment by pszufe** [comment]
@tbarton782 we have prepared a testing version 1.2.1
Perhaps you could have a look if it works for you as intended (for your decision tree).
If it works for you than after our test we will make it to an official release.
The temporary address of testing version is:
http://wasiluk.io/SilverDecisions/

**Comment by tbarton782** [comment]
That works perfectly.  Thank you for fixing it.

**Comment by paolocherubini** [comment]
Excuse me, but even though the lipping in the revised version 1.2.1 actually works (thank you), the current version published on https://silverdecisions.pl/ is apparently the old one, and flipping in it still does not work. I need flipping to teach diagnostic-test reading to my students... can you please publish the working version on the main silverdecision website?

**Comment by bkamins** [comment]
Fixed. Can you please check if all works OK? Thank you!

**Comment by paolocherubini** [comment]
Yes, now it works. Thank you Bogumil!

Il giorno mer 31 ago 2022 alle ore 21:48 Bogumił Kamiński <
***@***.***> ha scritto:
