### ISSUE TITLE
Request to make Silver decisions Https secured

### ISSUE THREAD

**Issue by rajnair1986** [SilverDecisions/SilverDecisions#213]
Dear Team, currently when we access http://silverdecisions.pl/ site, the site is not SSL certified. This is causing issues with accessing. Kindly assist to make this site https certified. Thanks in advance.

**Comment by bkamins** [comment]
@pszufe - can you please comment (my limited understanding is that someone would have to pay for SSL - right + if someone needs to use SilverDecisions in environment requiring certification it is possible to just download the whole software and host it locally?). Thank you!

**Comment by rajnair1986** [comment]
Hope this helps below. By the way the hosting should be secure.
Importance of HTTPS - https://doesmysiteneedhttps.com/
**Advantages of HTTPS:**
1. HTTPS protects users against [Man In the Middle attacks](https://freshman.tech/the-value-of-https/#https-prevents-man-in-the-middle-attacks).
2. HTTPS is required to leverage many [new features in browsers](https://freshman.tech/the-value-of-https/#many-browser-features-are-exclusive-to-https) such as Service Workers
3. HTTPS impacts [SEO](https://freshman.tech/the-value-of-https/#https-can-provide-seo-benefits)

**Comment by bkamins** [comment]
done

**Comment by rajnair1986** [comment]
Excellent. Thank you
