### ISSUE TITLE
Accessing Sensitivity Analysis

### ISSUE THREAD

**Issue by PLB11** [SilverDecisions/SilverDecisions#219]
I am a new user and find the software very useful.  However, one question.  I would like to use the sensitivity analysis features, but I do not appear to be able to access it.  In the documentation it says: 'Access "Sensitivity analysis" button in top menu (icon with three white bars on black background). '  I do not seem to be able to find the three white bars.  I am using a Chrome browser.  Can you help?

**Comment by bkamins** [comment]
To access sensitivity analysis you need both: a) a valid tree in main pane, b) a global variable on which you want to do sensitivity analysis.

@pszufe - do we have this covered in the book?

**Comment by PLB11** [comment]
Thanks for the quick reply.  However, I still have a problem.  In Section 7 of the documentation it states: "You start sensitivity analysis using "Sensitivity analysis" button in top menu (icon with three white bars on black background). “

My problem is that I cannot locate the icon with three bars.  I am accessing your program on my iMac via a Chrome browser.

Sorry to bother you with such a naive question, but I really would appreciate some help.  Your program is really quite excellent, and I would like to start using all of its features.

Regards,

Paul Brizzolara

**Comment by bkamins** [comment]
I have marked them with red circle in the picture below:
![image](https://user-images.githubusercontent.com/6187170/178200305-b07da938-6ba4-4b1d-8705-8b52ef08ac6e.png)
They are gray because in my screenshot there is no global variable defined to run sensitivity analysis on.

See also chapter 3.3 in the book https://ssl-administracja.sgh.waw.pl/pl/OW/publikacje/Documents/ModellingDecisionTreesWithSilverDecisions20220518_PRINT%20NEW_CMYK.pdf

**Comment by PLB11** [comment]
Bogumit,

Many thanks for the response.  I am still a problem getting the sensitivity module to run.  For some reason I was not able to access chapter 3.3 of the book you referenced.  When I try to access it I get a 404 error.

My apparent problem is that to access the sensitivity module I need to establish at least one global variable.  I have tried, I do not appear to understand how to establish a global variable

I would much appreciate your help either: 1) providing instructions for setting global variables, or 2) sending me a pdf for chaper 3.3 in the book you referenced.

Your continued patience with my is much appreciated.

Regards,

Paul Brizzolara

**Comment by bkamins** [comment]
Try this link to get the book please; https://szufel.pl/Modeling_Decision_Trees_with_SilverDecisions_2022_edited_by_P_Szufel_M_Jakubczyk_B_Kaminski.pdf
