### ISSUE TITLE
Is there a way to run silverdecisions offline?

### ISSUE THREAD

**Issue by paolocherubini** [SilverDecisions/SilverDecisions#224]
I'm using silverdecisions for my course of evidence based practice in psychology, but my classroom has bad wifi and the software runs slow (or blocks). Is there any way to download a offline-working version?

**Comment by bkamins** [comment]
The software doe not require Internet connection to run. But you need Internet connection to load the page with it.

Technically it is also possible to configure it to run in a browser from a local file (but this is a bit technically complicated), but it would require downloading it anyway. So if you need to download it it is recommended to just to load it in the browser.

**Comment by paolocherubini** [comment]
Thank you, if once loaded the page it runs even without connection, this solves most of the problem
