### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#34]
@mwasiluk would adding export to PDF be a problem (we can live with export to SVG if it would be fixed for IE/Edge if it is too complex to implement)?

**Comment by pszufe** [comment]
Michal - maybe postscript would be an easier  option than pdf instead of SVG?

**Comment by bkamins** [comment]
@pszufe please decribe the problems you have with SVG so that they can be reproduced.

To sum up - we need some way of having reliable a vector graphics output from SilverDecisions. It can be SVG, PDF or PS. Now we have SVG but it does not integrate well with some external tools (@pszufe will describe which and why).

**Comment by pszufe** [comment]
It should be possible to handle *.SVG files with graphic software.
Seems that the State of art is Incspace (can be used as GUI or command line)
inkscape -z -D --file sampleTree.svg --export-pdf sampleTree.pdf --export-latex
Unfortunatelly the result is very poor (image is black&white and some lines are missing). 

Another reasonable option (Bogumil - read this and confirm that it would be enough) - and here I think we are closer would be GIMP. GIMP does not support vector graphics but is able to convert SVG to 600dpi o r 1200dpi image - which is totally enough for publishing quality. 
When I open SVG in GIMP everything is OK except for the exclamation marks (!!) - they are not visible in the browser yet they are being displayed in SVG. Maybe we can just somehow get rid of exclamation marks - than it should be possible to run a gimp on command to make the conversion (it would even be possible to configure it so it happens during LaTeX compile time - I have seen similar solutions for inkspace and we probably could copy it).

**Comment by bkamins** [comment]
@pszufe if you want raster then why PNG is not enough for you? At least on my laptop it has a decent resolution.

**Comment by pszufe** [comment]
@bkamins why you want vector?

**Comment by bkamins** [comment]
@pszufe because we already have a good raster export to PNG, and the only thing we are missing is good vector export - sometimes it is the only way to go (eg. printing tree on a very large poster). If you do not need vector graphics PNG export is good enough for you in my opinion.

**Comment by pszufe** [comment]
@mwasiluk we have had a phone discussion with @bkamins and the conclusion is following.
1. SilverDecisions users want to have possibility to print decision trees (e.g. on a large poster)
2. Most suited is vector graphics/PDF but there is  a problem it probably will be hard to repair (unless we come across a god PDF/vector library for JavaScript canvas) 
3. A "good enough" solution that seems to satisfy all users is the following:
  - make SVG fine for GIMP (ie get rid of exclamation marks in such a way that SVG after importing to GIMP will look properly)
   - @annawier will prepare a documentation section on how to process SVG through GIMP in order to get a print-quality raster graphics (i.e. 600 dpi at any print-out size required by the user for their publishing needs)

**Comment by bkamins** [comment]
Not working under IE (but handled correctly so it is acceptable)

Under Chrome and Edge on Windows 10 two problems:
- Polish letters (and probably also other non-latin characters) are not saved properly
- arrow tips are too small

**Comment by mwasiluk** [comment]
One way to generate proper pdf currently is to save SVG and convert it with some tool, e.g.:
http://www.fileformat.info/convert/image/svg2pdf.htm
[test.pdf](https://github.com/bkamins/SilverDecisions/files/664691/test.pdf)

**Comment by mwasiluk** [comment]
It seems that jsPDF doesn't support UTF-8 ;/
https://github.com/MrRio/jsPDF/issues/12

**Comment by bkamins** [comment]
I assume that arrow-tips problem can be solved and concentrate on the Unicode.
@mwasiluk If I understand this correctly we have the following options:
1) leave it as is (and document that we do not support Unicode)
2) switch to pdfkit (should work, but is too heavy and probably I would recommend loading pdfkit on demand only) or pdfmake (I do not know if it has the functionality we need)
3) when PDF button is pressed show popup with instruction to generate SVG and convert it to PDF (and tell how); we have to tell how as we should test the integration of the tool with generated SVG; eg. the tool you give does not work for release 0.4 and for dev wrong size of canvas is taken (to much white space around the tree is generated)

Please let me know what you feel is the best way to go (for me option 1 is worst, option 2 is bets, but option 3 is acceptable).

**Comment by mwasiluk** [comment]
It seems that pdfkit has support only for svg paths, not for rendering whole svg from string. 
There is an SVG renderer for PDFKit side project https://github.com/devongovett/svgkit but it's unfinished.

W could also try to detect unicode characters in the diagram and then render pdf on the server.
Maybe we could use http://export.highcharts.com or set our own server:
http://www.highcharts.com/docs/export-module/setting-up-the-server
https://github.com/highcharts/node-export-server

I've tested export.highcharts.com with SilverDecisions and it seems to render pdfs correctly.

Highcharts Node.js export server is MIT licensed
We could also implement fallbacks to export server for older browsers, like in highcharts

**Comment by bkamins** [comment]
If high charts works I am OK with this and ok to use their server. We could even probably have a fallback for `PNG` where it dose not work to their server also?

As for license: I understand that for non-commercial use (as is our case) it is free and under CC BY-NC 3.0 license, MIT is only if we wanted to setup our own server (and MIT is very liberal so this should not be a problem).

@mwasiluk What is the benefit of own server? (I would prefer to use their server as then we do not have to think about maintenance)

@pszufe Given this discussion are there any licensing restrictions in ROUTE2PA?

**Comment by mwasiluk** [comment]
We wouldn't use highcharts, only their export server

**Comment by bkamins** [comment]
The current consensus is that:
1) we use export.highcharts.com
2) @annawier we have to add to documentation that not always fonts will be the same in PDF (when PDF renderer does not have them)
3) in the future we might switch to our own server, but this is not a priority (maybe someday @pszufe will want to setup a server on Amazon)
4) on systems where PNG generation fails we can use the same method
5) @mwasiluk will work on optimizing size and portability of generated SVG

**Comment by bkamins** [comment]
@mwasiluk Excellent work.

@annawier Please document the following things:
- PDF export is via external converter
- PNG is supported now under IE (also via external converter)

The external converter is: http://export.highcharts.com.

Additionally users should be informed that:
- the recommended export format is SVG as it guarantees exactly the same image as seen in the browser and it is fastest
- PDF might look a bit different (we cannot guarantee that the same fonts are used)
- in general export preserves selection (i.e. if something is selected in the view it will be exported as selected)

**Comment by annawier** [comment]
documented

2016-12-21 20:34 GMT+01:00 Bogumił Kamiński <notifications@github.com>:

**Comment by annawier** [comment]
"fonts which are **not** on PDF renderer server will **not** be substituted by alternatives in exported PDF file." --> shouldn't be: "fonts which are **not** on PDF renderer server will be substituted by alternatives in exported PDF file."?

**Comment by bkamins** [comment]
thx
