### ISSUE TITLE
Strict division into modules

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#95]
@mwasiluk For 1.0 release the following is initial draft of separation of SilverDecisions code into components: https://www.overleaf.com/read/pfqynqqdyndw.

**Comment by pszufe** [comment]
The project is now divided into 6 separate modules:
    sd-tree-designer - decision tree designer module, responsible for tree visualisation and construction
    sd-computations - module responsible for all more complex computations (e.g. objective rules, sensitivity analysis)
    sd-model - data model representation and simple operations on the decision tree model
    sd-expression-engine - expression engine implementation (based mainly on Math.js)
    sd-utils - shared utils module
    sd-random - tools for generating random numbers from various distributions 

The description can be found at:
https://github.com/SilverDecisions/SilverDecisions/wiki/Developer's-guide#project-structure
