### ISSUE TITLE
add generators for non-uniform pseudorandom variables

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#98]
We should add this either via some external library (@mwasiluk) or @bkamins will write custom extensions if needed.
We roughly want the following distributions (this is flexible):
* normal
* exponential
* triangular
* trapezoidal
* uniform on any interval
* beta
* gamma
* Bernoulli
* binomial
* discrete uniform
* geometric
* Poisson

**Comment by bkamins** [comment]
@pszufe will implement it

**Comment by bkamins** [comment]
@pszufe - excellent. I would only ask to add strict parameters checking (if they have correct types and correct ranges, eg. negavie std in normal, on negative lambda in exponential) -> in such cases NaN should be produced.

@mwasiluk - it is implemented in https://github.com/SilverDecisions/sd-random.
1. please check if definition of `random()` does not offend definition of `random` in MathJS, if it does let @pszufe know and we should remove it.
2. sd-random defines variable `menu_list` that should be used to populate examples in drop down menu in probabilistic SA (user can use one of them, but then can freely edit the result) - implement it in the most convenient way.
3. please advise @pszufe how to wrap the code to make it a package and then integrate it with whole SD (or simply correct the code yourself if this is faster than explaining)

**Comment by mwasiluk** [comment]
The gamma function collides with math.js implementation:
http://mathjs.org/docs/reference/functions/gamma.html

**Comment by bkamins** [comment]
@mwasiluk The decision is to:
1. rename all functions to uppercase;
2. remove `random` from menu list
I will implement both changes in the source code of `sd-random`.

@pszufe what is the status of implementation of checks of types and ranges of arguments?

**Comment by bkamins** [comment]
@mwasiluk drop down:
* under Chrome does not show properly (it seems as if it was shown below the dialog)
* under IE shows properly, but after selection an error is reported and the computations do not start

should I send screenshots?

**Comment by mwasiluk** [comment]
It should look like this on Chrome:
![sd-drop-dow](https://cloud.githubusercontent.com/assets/1236142/25152703/36bc5ef8-248a-11e7-9492-724cd9efa938.png)

**Comment by bkamins** [comment]
I know, but it looks like this (observe Gamma in the background):
![image](https://cloud.githubusercontent.com/assets/6187170/25152846/b08ff578-248a-11e7-8f4f-e08cda0c0d4b.png)

**Comment by mwasiluk** [comment]
Strange; Are there any errors in the console after page reload?

**Comment by bkamins** [comment]
There are two warnings when the page loads:
```
DevTools failed to parse SourceMap: http://bogumilkaminski.pl/sddev/silver-decisions-vendor.min.js.map
DevTools failed to parse SourceMap: http://bogumilkaminski.pl/sddev/silver-decisions-core.min.js.map
```
but probably this is unrelated.

@pszufe Can you test it?

**Comment by bkamins** [comment]
It works under Chrome now so I am closing this and leaving #113 open.
